
### Summary

```{r, fig.align='center', fig.pos='htb!', echo=FALSE, cache=FALSE, warning = FALSE, message = FALSE, tidy=TRUE}

datatable(getOverview(), rownames = F, options = list(dom = 't',ordering = F),
          width = 350)


```

### Data inspection

```{r, fig.align='center', fig.pos='htb!', echo=FALSE, cache=FALSE, warning = FALSE, message = FALSE, tidy=TRUE}

getpca2d()


```

### Differential expression analysis


```{r, fig.align='center', fig.pos='htb!', echo=FALSE, cache=FALSE, warning = FALSE, message = FALSE, tidy=TRUE}

datatable(getReg(), rownames = F, options = list(dom = 't',ordering = F),
          width = 200)
```

### Functional analysis

#### Upregulated pathways
```{r, fig.align='center', fig.pos='htb!', echo=FALSE, cache=FALSE, warning = FALSE, message = FALSE, tidy=TRUE}

datatable(getUpPathways(), rownames = F, options = list(dom = 't',ordering = T),
          width = 350)


```

#### Downregulated pathways
```{r, fig.align='center', fig.pos='htb!', echo=FALSE, cache=FALSE, warning = FALSE, message = FALSE, tidy=TRUE}

datatable(getDownPathways(), rownames = F, options = list(dom = 't',ordering = T),
          width = 350)


```

#### Volcano

```{r, fig.align='center', fig.pos='htb!', echo=FALSE, cache=FALSE, warning = FALSE, message = FALSE, tidy=TRUE}
library(plotly)

vv <- getVolcano()

plotly::ggplotly(vv$v) %>%
            layout(dragmode = "select")



```


