---
title: "Upload annotation data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Expected format

Uploading annotation data is optional and not necessary to run the analysis. In the annotation file, the first column should include the name of each sample, as they are represented in the data file. The remaining columns should describe a phenotype, or a property of the sample. For example, the columns could describe patient characteristics such as sex, age, and BMI.

### Example

The annotation file for a dataset with 2 conditions and 10 replicates could look like the following:

Sample | Sex | Age | BMI
---- | ---- | ----| ---- |---- 
TREATMENT_001 | Female | 77 | 22.3
TREATMENT_002 | Male | 58 | 33.2
TREATMENT_003 | Female | 74 | 25.5
TREATMENT_004 | Male | 43 | 42.4
TREATMENT_005 | Male | 50 | 34.2
TREATMENT_006 | Female | 18 | 16.4
TREATMENT_007 | Male | 49 | 33.0
TREATMENT_008 | Female | 32 | 22.8
TREATMENT_009 | Female | 61 | 23.3
TREATMENT_010 | Male | 52 | 26.8
CONTROL_001 | Female | 77 | 22.3
CONTROL_002 | Male | 58 | 33.2
CONTROL_003 | Female | 74 | 25.5
CONTROL_004 | Male | 43 | 42.4
CONTROL_005 | Male | 50 | 34.2
CONTROL_006 | Female | 18 | 16.4
CONTROL_007 | Male | 49 | 33.0
CONTROL_008 | Female | 32 | 22.8
CONTROL_009 | Female | 61 | 23.3
CONTROL_010 | Male | 52 | 26.8